MakeyMakey.sx1509_init()
MakeyMakey.typeKey(MakeyMakey.KeyPress.W)
MakeyMakey.typeKey(MakeyMakey.KeyPress.A)
MakeyMakey.typeKey(MakeyMakey.KeyPress.S)
MakeyMakey.typeKey(MakeyMakey.KeyPress.D)
MakeyMakey.typeKey(MakeyMakey.KeyPress.F)
MakeyMakey.typeKey(MakeyMakey.KeyPress.G)
MakeyMakey.clickMouse(MakeyMakey.MouseButtons.RIGHT)
MakeyMakey.moveMouseForSeconds(MakeyMakey.MouseDirections.LEFT, 500)
MakeyMakey.clickMouse(MakeyMakey.MouseButtons.LEFT)
MakeyMakey.moveMouseForSeconds(MakeyMakey.MouseDirections.RIGHT, 500)
MakeyMakey.moveMouseForSeconds(MakeyMakey.MouseDirections.UP, 500)
MakeyMakey.moveMouseForSeconds(MakeyMakey.MouseDirections.DOWN, 500)
