MakeyMakey.sx1509_init()
MakeyMakey.typeKey(KeyPress.W)
MakeyMakey.typeKey(KeyPress.A)
MakeyMakey.typeKey(KeyPress.S)
MakeyMakey.typeKey(KeyPress.D)
MakeyMakey.typeKey(KeyPress.F)
MakeyMakey.typeKey(KeyPress.G)
MakeyMakey.clickMouse(MouseButtons.RIGHT)
MakeyMakey.moveMouseForSeconds(MouseDirections.LEFT, 500)
MakeyMakey.clickMouse(MouseButtons.LEFT)
MakeyMakey.moveMouseForSeconds(MouseDirections.RIGHT, 500)
MakeyMakey.moveMouseForSeconds(MouseDirections.UP, 500)
MakeyMakey.moveMouseForSeconds(MouseDirections.DOWN, 500)
